<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php
$array = [
    [
        'year'=>'2021',
        'month'=> '6',
        'day' => '11',
        'hours' => '11',
        'minutes'=>'43',
        'seconds'=>'10'
    ],
    [
        'year'=>'2020',
        'month'=> '6',
        'day' => '6',
        'hours' => '4',
        'minutes'=>'20',
        'seconds'=>'2'
    ],
    [
        'year'=>'2029',
        'month'=> '3',
        'day' => '25',
        'hours' => '16',
        'minutes'=>'00',
        'seconds'=>'12'
    ],
    [
        'year'=>'2021',
        'month'=> '6',
        'day' => '10',
        'hours' => '12',
        'minutes'=>'30',
        'seconds'=>'12'
    ]
];
foreach($array as $key => $value) {
    ?>
    <p>
        <?= ($value['year'] == '2029') ?
            $block->escapeHtml($value['year'] . ' - Year')
            : $block->escapeHtml('Year - ' . $value['year']) ?>
    </p>
    <p>
        <?= $block->escapeHtml('Month - ' . $value['month']) ?>
    </p>
    <p>
        <?= $block->escapeHtml('Day - ' . $value['day']) ?>
    </p>
    <p>
        <?= $block->escapeHtml('Time: ' . $value['hours'] . ':' . $value['minutes'] . ':' . $value['seconds']) ?>
    </p>
<?php
}
?>
