<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div data-bind="scope: 'graphSlider'">
    <form>
        <label><?= $block->escapeHtml(__('Name'))?>
            <input data-bind="value: inputProductName">
        </label>
        <label><?= $block->escapeHtml(__('Quantity'))?>
            <input data-bind="value: inputQuantitySlides">
        </label>
        <button data-bind="click: renderCustomProductSlider.bind($data)">
            <?= $block->escapeHtml(__('Show Products'))?>
        </button>
    </form>
    <div class="product-slider">
        <!-- ko foreach: products -->
        <div class="item-product">
            <img style="height: 150px" data-bind="attr: {src: image.url}">
            <div class="product-info">
                <p data-bind="text: name"></p>
                <p>Price: <span data-bind="text: price_range.minimum_price.regular_price.value"></span></p>
                <p>SKU: <span data-bind="text: sku"></span></p>
            </div>
        </div>
        <!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "graphSlider": {
                    "component": "js/graph-slider"
                }
            }
        }
    }
}
</script>
