<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<div data-bind="scope: 'selectorCity'">
    <span>
        <?= $block->escapeHtml(__('Choose city')) ?>
    </span>
    <select name="selectCity" data-bind="options: availableCities,
                                         optionsText: 'label',
                                         value: selectedCity">
    </select>
</div>
<div data-bind="scope: 'selectorStore'">
    <span><?= $block->escapeHtml(__('Choose seller')) ?><span>
    <div data-bind="foreach: availableSellers">
        <div>
            <input type="checkbox" data-bind="value: $data, checked: $parent.checkedSellers" />
            <span data-bind="text: $data"></span>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "selectorCity": {
                        "component": "js/selector-city"
                    },
                    "selectorStore": {
                        "component": "js/selector-store"
                    }
                }
            }
        }
    }
</script>
