<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
$cssClass = $block->hasCssClass() ? $block->getCssClass() : '';
$elementContent = $block->hasElementContent() ? $block->getElementContent() : '';
?>

<div class="<?= $block->escapeHtmlAttr($cssClass) ?>">
    <?= $block->escapeHtml(__($elementContent)) ?>
</div>
