<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "js/second-js-module":{},
            "Magento_Ui/js/core/app": {
                "components": {
                    "firstUiComponent": {
                        "component": "js/first-js-ui-component"
                    }
                }
            }
        }
    }
</script>
