<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Customer $block */
?>
    <?php if ($block->customerLoggedIn()): ?>
    <p>
        <?= $block->escapeHtml(__('Customer is logged in!')) ?>
    </p>
    <?php else: ?>
    <p>
        <?= $block->escapeHtml(__('Customer is not logged in!')) ?>
    </p>
    <?php endif; ?>

