<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading" data-bind="scope: 'checkEmailExists' ">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'
        <?= $block->getBlockHtml('formkey') ?>
        <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="login[username]" data-bind="value: userEmail"
                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                           id="email" type="email" class="input-text"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}">
                    <p data-bind="text: checkMessage"></p>
                    <button class="check-email-button" type="button" data-bind="click: checkEmail, visible: isCheckEmailVisible">
                        <?= $block->escapeHtml(__('Check Email')) ?>
                    </button>
                </div>
            </div>
            <div class="primary" data-bind="visible: isCreateAccountVisible" style="display: none">
                <a href="<?= $block->escapeHtmlAttr($block->getUrl("customer/account/create")) ?>" class="action create primary">
                    <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
                </a>
            </div>
            <div class="field password required" data-bind="visible: isPasswordVisible" style="display: none">
                <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <input name="login[password]" type="password"
                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                           class="input-text" id="pass"
                           title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           data-validate="{required:true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
            <div class="actions-toolbar" data-bind="visible: isPasswordVisible" style="display: none">
                <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
            </div>
        </fieldset>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "login-form"
            },
            "Magento_Ui/js/core/app": {
                "components": {
                    "checkEmailExists": {
                        "component": "js/check-email-exists"
                    }
                }
            }
        }
    }
</script>
